version: "2.7"

volumes:
  db-data:

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
    ports:
      - "15506:3306"
    expose:
      - "3306"
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: rails-studie-cable-web
    stdin_open: true
    tty: true
    depends_on:
      - db
    env_file:
      - .env
      - docker/docker.env
    ports: 
      - "5500:3000"
    volumes:
      - .:/app
